# Generated by Django 4.2.4 on 2023-09-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lists',
            options={'verbose_name_plural': 'Lists'},
        ),
        migrations.AddField(
            model_name='lists',
            name='list_date',
            field=models.DateField(null=True),
        ),
    ]
